
#spring.datasource.url=jdbc:mysql://localhost:3306/studentdb

#spring.jpa.hibernate.ddl-auto=create

#spring.jpa.show-sql=true

# spring.datasource.username=root

#spring.datasource.password=root

server:
 port: 8080

spring:
 profiles:
  active : prod
 datasource:
  username : root
  password: root
  url: jdbc:mysql://localhost:3306/studentdb
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
 security :
  user:
   name : scott
   password: tiger
# management.endpoints.web.exposure.include=*

management:
 endpoints:
  web:
   exposure:
    include : '*'
  
  
info:
 projectName: Student Management Application
 created By : Sharad Rajore
 
# spring.security.user.name=

#spring.security.user.password=
 


  
  
